In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np

#### Creating Numpy array


In [7]:
# np.array()

In [13]:
# for 1D array
list1=[1,2,4,5]
arr=np.array(list1)
print(type(arr))
print(arr.ndim)

<class 'numpy.ndarray'>
1


In [16]:
# for 2d array
list2=[
        [1,2,3],
        [2,3,4],
        [4,5,6]
]

arr=np.array(list2)
print(type(arr))
print(arr)
print(arr.ndim)

<class 'numpy.ndarray'>
[[1 2 3]
 [2 3 4]
 [4 5 6]]
2


In [17]:
# np.zeros() 
# 1D

array_zero = np.zeros(5)
print(array_zero)

[0. 0. 0. 0. 0.]


In [18]:
# np.zeros() 

array_zero = np.zeros((2,3))
print(array_zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
# np.ones()
# 1D
array_ones = np.ones(5)
print(array_ones)

[1. 1. 1. 1. 1.]


In [20]:
# np.ones()
# 1D
array_ones = np.ones((2,3))
print(array_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [23]:
# np.full()
# 1D
array_full = np.full(shape = 5, fill_value = 3 )
print(array_full)

print(array_full.dtype)

[3 3 3 3 3]
int64


In [22]:
# np.full()

array_full = np.full(shape = (2,3), fill_value = 5 )
print(array_full)

print(array_full.dtype)

print(array_full.shape)

[[5 5 5]
 [5 5 5]]
int64
(2, 3)


In [24]:
# range(<start>, <end>, <step>)
list(range(1,10, 2))

[1, 3, 5, 7, 9]

In [25]:
# np.arange(start, stop, step)
# Can only define array of 1D

array_range1 = np.arange(1,10)
print(array_range1)

[1 2 3 4 5 6 7 8 9]


In [31]:
# np.linspace(start, stop, element) > linear space

array_linspace1 = np.linspace(start=0, stop=10, num=5)
print(array_linspace1)

[ 0.   2.5  5.   7.5 10. ]


In [34]:
array_linspace2 = np.linspace(start= (0,0,0), stop= (10,20,30), num=5, axis =1)
print(array_linspace2)

[[ 0.   2.5  5.   7.5 10. ]
 [ 0.   5.  10.  15.  20. ]
 [ 0.   7.5 15.  22.5 30. ]]


In [36]:
# np.diag() > Square matrix

diag_array1= np.diag([1,2,3])
print(diag_array1)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [38]:
diag_array1= np.diag([4,5,6,7], k =-2)
print(diag_array1)

print(diag_array1.dtype)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [4 0 0 0 0 0]
 [0 5 0 0 0 0]
 [0 0 6 0 0 0]
 [0 0 0 7 0 0]]
int64


In [39]:
# np.eye() diagonal matix with 1
eye_array1 = np.eye(N = 5, M=4)
print(eye_array1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [41]:
# np.identity()
# diagonal matrix with 1  > identity matrix
# less used in industry
identity_array = np.identity(5)
print(identity_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [42]:
# np.random
random_array = np.random.rand(1,2,5)
print(random_array)
print(random_array.ndim)

[[[0.99658534 0.32345353 0.51764478 0.10666022 0.19615459]
  [0.96373423 0.30986741 0.41463677 0.37974101 0.0230635 ]]]
3


In [54]:
random_array = np.random.randint(low = 10, high = 50, size = (2,3,4))
print(random_array)
print(random_array.ndim)

[[[12 26 32 16]
  [17 33 11 32]
  [46 17 23 17]]

 [[48 30 46 30]
  [35 18 47 39]
  [26 40 35 46]]]
3


In [55]:
print(random_array.shape)

(2, 3, 4)


1D Array: array_name[idx] (Similar to Python list)

2D Array: array_name[row_idx, col_idx] (Similar to Matrix)

ND Array: array_name[dim1_idx, dim2_idx, ..., dimN_idx]

#### Indexing Numpy Array

##### One Dimension

In [66]:
list1=[1,2,3,4,5]
arr1=np.array(list1)
print(arr1)
print(arr1[2])


[1 2 3 4 5]
3


##### Multi Dimension

In [67]:
arr=np.array([[1,2,3],[2,3,4]])
print(arr)

[[1 2 3]
 [2 3 4]]


In [69]:
arr.shape

(2, 3)

In [70]:
arr[1][2]

np.int64(4)

In [71]:
random_array = np.random.randint(low = 10, high = 50, size = (6,3,3))
print(random_array)

[[[46 47 20]
  [28 16 22]
  [13 16 38]]

 [[44 37 46]
  [22 33 25]
  [44 49 41]]

 [[39 42 16]
  [29 41 20]
  [41 46 31]]

 [[10 39 27]
  [24 44 43]
  [27 33 18]]

 [[27 21 14]
  [43 42 23]
  [23 43 43]]

 [[20 15 24]
  [19 12 45]
  [12 33 26]]]


In [75]:
print(random_array[3,2,1])

33


#### Slicing Numpy array

##### 1D

In [76]:
list2 = [4,7,0,45,67,8, 66.2]

In [77]:
list2[:-1] #list2[start index : stop index : step ]

[4, 7, 0, 45, 67, 8]

In [78]:
slice_array = np.array(list2)
print(slice_array)

[ 4.   7.   0.  45.  67.   8.  66.2]


In [79]:
slice_array[:-2:2]

array([ 4.,  0., 67.])

##### 2D

In [80]:
list2d = [[1, 2, 3, 4, 5, 6, 7, 8], [1, 3, 5, 7, 9, 11, 13, 15]]
slice2d_array = np.array(list2d)
print(slice2d_array)

[[ 1  2  3  4  5  6  7  8]
 [ 1  3  5  7  9 11 13 15]]


In [81]:
slice2d_array[0, 2:]

array([3, 4, 5, 6, 7, 8])

In [82]:
list2d = [[1, 2, 3, 4, 5, 6, 7, 8], [1, 3, 5, 7, 9, 11, 13, 15], [15, 25, 9999, 376, 19, 420, 786, 555]]
slice2d_array = np.array(list2d)
print(slice2d_array)

[[   1    2    3    4    5    6    7    8]
 [   1    3    5    7    9   11   13   15]
 [  15   25 9999  376   19  420  786  555]]


In [84]:
slice2d_array[1:,4:7]


array([[  9,  11,  13],
       [ 19, 420, 786]])

##### 3D

In [91]:
rarr=np.random.randint(low=10,high=50,size=(4,3,4))
print(rarr)

[[[36 33 22 12]
  [44 47 39 34]
  [41 45 37 26]]

 [[26 37 34 33]
  [14 15 24 29]
  [49 20 38 11]]

 [[32 49 34 27]
  [33 10 13 49]
  [43 31 10 26]]

 [[14 13 30 45]
  [38 34 44 23]
  [35 18 28 47]]]


In [94]:
random_array[-2:,:2,:2]

array([[[27, 21],
        [43, 42]],

       [[20, 15],
        [19, 12]]], dtype=int32)

#### Numpy attribute

In [96]:
arry = np.random.randint(low = 10, high = 50, size = (3,6))
arry1 = np.random.randint(low = 10, high = 50, size = (4,6))
print(arry)
print()
print(arry1)

[[13 42 25 34 22 24]
 [45 31 12 14 31 40]
 [39 48 33 22 18 16]]

[[37 13 25 31 26 13]
 [24 31 14 45 13 38]
 [19 33 25 20 11 12]
 [37 33 26 38 14 21]]


In [99]:
print(arry.shape)
print(arry.size)
print(arry.ndim)
print(arry.dtype)
print(arry.T)

(3, 6)
18
2
int32
[[13 45 39]
 [42 31 48]
 [25 12 33]
 [34 14 22]
 [22 31 18]
 [24 40 16]]


In [107]:
print(arry.sum(axis=0))
print(arry.max(axis=1))
print(arry.argmax(axis=1))
print(arry.flatten())
print(arry.reshape(3,6))

[ 97 121  70  70  71  80]
[42 45 48]
[1 0 1]
[13 42 25 34 22 24 45 31 12 14 31 40 39 48 33 22 18 16]
[[13 42 25 34 22 24]
 [45 31 12 14 31 40]
 [39 48 33 22 18 16]]


In [108]:
# Concatenate
m = np.array([[1, 2], [3, 4]])
n = np.array([[5, 6], [7, 8]])

print(m)
print("="*20)
print(n)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [110]:
np.concatenate((m,n), axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [111]:
a = np.array([[4, 5, 6], [5, 7, 9]])
b = np.array([[1, 2, 3], [9, 8,7 ]])

In [112]:
print(a)
print("-"*20)
print(b)

[[4 5 6]
 [5 7 9]]
--------------------
[[1 2 3]
 [9 8 7]]


In [113]:
a+b

array([[ 5,  7,  9],
       [14, 15, 16]])

In [114]:
b-a

array([[-3, -3, -3],
       [ 4,  1, -2]])

#### Matrix Operations

In [115]:
a = np.array([[8, 5, 6, 7], [5, 73, 7,8]])
b = np.array([[1, 2, 7,8], [97,8,8, 8], [1, 2, 7,8], [97,8,8, 8]])

In [116]:
print(a)
print("-"*20)
print(b)

[[ 8  5  6  7]
 [ 5 73  7  8]]
--------------------
[[ 1  2  7  8]
 [97  8  8  8]
 [ 1  2  7  8]
 [97  8  8  8]]


In [117]:
np.dot(a,b)

array([[1178,  124,  194,  208],
       [7869,  672,  732,  744]])

In [118]:
np.transpose(a)

array([[ 8,  5],
       [ 5, 73],
       [ 6,  7],
       [ 7,  8]])

In [119]:
a_22 = np.array([[8, 5], [5, 7]])

np.linalg.det(a_22)

np.float64(31.0)

#### Numpy Broadcasting

The rules of broadcasting are as follows:

1.If the arrays have different numbers of dimensions, the smaller array is padded with ones on its left until it has the same number of dimensions as the larger array.

2.If the shape of the arrays does not match along any dimension, the array with shape equal to 1 along that dimension is stretched to match the shape of the other array.

3.If the arrays still do not match in shape, an error is raised.

In [120]:
a = np.array([[1, 2], [3, 5]])
b = np.array([10, 20])

In [121]:
a , a.shape

(array([[1, 2],
        [3, 5]]),
 (2, 2))

In [124]:
b, b.shape

(array([10, 20]), (2,))

In [125]:
a+b

array([[11, 22],
       [13, 25]])